[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "e67b7d24f27e1c67304fc8aacac287c6b74abafd"
os = "macos"

    [[armadillo.download]]
    sha256 = "6c3678aa3f464128fb22d7b5602ff28df5e501c1f33912c7e8408c15f2414d18"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.aarch64-apple-darwin.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "cff5e2f30c1ef7e1578a55acc1749832373b4eb1"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "0ec831935ac88fe09e264532e1c35240f3066b4c6eae7d40d60a77f9937c8fbe"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.aarch64-linux-gnu.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "f510d7fa6fefa0cb8cef29950041f5a6944b19f4"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "5328aa8ff6a8468fb56964367166868dada5e1a4e8bc71ae1e5662c3f267679e"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.aarch64-linux-musl.tar.gz"
[[armadillo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a75f589128ca878de4b34b0415485454ccdb32c5"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "e4d91acbbd7fa51fba2ff10e7c4827fc52cb262819f83a0115e0f3c3bd1ee445"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.armv6l-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a4454ab83ffa43db88d0e966202e042cba5a0e82"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "c88e09f5859c7203ceff50b46848105db34a1594219d08600918994e9e0a7e86"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.armv6l-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d91bbcc75e98c3caebff649dd00ac7833fc06c7e"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "1f5afe882385e084dcd17e878fee51c9463c91de8fd7d080062444dc5f2c80cf"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.armv7l-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0ca0dd8cb956fb7e5fd62941d851d8996560d244"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "45997ab7a12de4308daf6055ec5758bd6e7e2a51cfea01af25059dc465e56ad8"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.armv7l-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "b5988c9bf166545125bde4b18af0c61d26a63127"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "dd5d0e5fda1ebd320bca71fd258a63274641b71eef685de44de15307c7361f5c"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.i686-linux-gnu.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "313df3deb544b5083799e58b974ca74d55288dce"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "185f8b7d970d302c5c8ae9e936e719eae200261661da81cbc3297c62bf09a507"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.i686-linux-musl.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "5c71a05549e02c1836dcdfbc1c5c48c2ed7a7b42"
os = "windows"

    [[armadillo.download]]
    sha256 = "aac1f2e836ef17c15f599aded4a87fbde3f7d4f16ad480d8ef897dcb64a15be6"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.i686-w64-mingw32.tar.gz"
[[armadillo]]
arch = "powerpc64le"
git-tree-sha1 = "81c3e13f29ae6f8dab830f4c66cfcf5cccb7d737"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "cbd761120f5f0d7f0ce7b57d1398e4cd615d7af829af944ff906c32768b93376"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.powerpc64le-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "6afb386abebc9624980906a7ac7723bf62bcab28"
os = "macos"

    [[armadillo.download]]
    sha256 = "ffedba4ca6d7c0844c234d59aa1df326fd847d82d0a3bf06fe01ff8193ca90df"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.x86_64-apple-darwin.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "1165df8cc76789e78cb07b13861f662703065535"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "f690a104ce1d148dcf025dc2a88ed072e80ad4751dcc396221e512668075f8a4"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.x86_64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "1541676d922ed46a561042a863143b757ea27e28"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "e8073a316753242245292113caf286cf1ce3f1e87153a948c639d2484ea2c3b0"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.x86_64-linux-musl.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "f59a86f5262d1ff7c7d793bd724a59fe25515b90"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "68935b730745a0598a58aa48ad608da47b6c74bba676061c5d51be2427b0857c"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.x86_64-unknown-freebsd.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "f83bfffddd2cd68260be7a96bf0d965631c07497"
os = "windows"

    [[armadillo.download]]
    sha256 = "28ab7f16bcaaa3d6cb99b53e99394e29b3a334b9a47f35c005f9df5afe05865d"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.8.3+0/armadillo.v12.8.3.x86_64-w64-mingw32.tar.gz"
