[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "c5b55a5b8259238306cf41e7dc99c97be053e77f"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "579b3e62311bcc8ce2ad929e58d27448ad051fbb77e429ba190d2065c1b7f2b5"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.aarch64-linux-musl.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "fd649bdf304f0e7398606fcadcf096dcfda12097"
os = "windows"

    [[armadillo.download]]
    sha256 = "ea60de6eeddb3569fc63bc5eae18669d88d73b3d5301fd7dc53e301ae6db36a0"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-w64-mingw32.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "abda53e81c53278c19dd31fe84a54ac7fa219dba"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "1c69036d8ad083559bbb9bb03e8c14024e82e82c406502cdeafea7ddc7f25e8f"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-linux-musl.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "cf823d69de22194d90a9f61156df497588aa85fb"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "d077bec22eb9d53bb542f08e94d51738fa1526b422290a448bd44df709c26168"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-linux-gnu.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "b8c2e41bf6a918a75705574ed958d2198916c22e"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "d46705cd38ac17dd18c8763522cbcf348b100c8768b510c524cb4f4400c0288c"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.armv7l-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "1541cbd55216ee1e992267aa4021719d75f0ad18"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "e3aae66082767fbf77ae0784ad32e85811b6f720484269fb8f4f97267c8647a5"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.aarch64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "a77858d29c9ec2cede31e88fd32d2f13048d6900"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "aea4a686a162eeac0d942efceb504af04ee732670b8dff0090a3984739f4083f"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-linux-gnu.tar.gz"
[[armadillo]]
arch = "powerpc64le"
git-tree-sha1 = "b96023484ceb690ad923f35033d9a5c09846fdb9"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "69bfc50b2fb0c02d299dabd9e0254b24cf8b383b92cc4d1cbf98586fcdf30530"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.powerpc64le-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "3fd7eb8149119a84a8454cf93dfa75d6c9734ece"
os = "macos"

    [[armadillo.download]]
    sha256 = "d734604f9f11097dc180b6d43cd744485ea17bab9aac671fe88be89221cd8349"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-apple-darwin14.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "ac462f22d44eee0f539073134c301702fa303593"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "1cbf6eea1899efe56fb9c8f9a7dcebdb2ce39c43d51acb695159f749256716ee"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-unknown-freebsd11.1.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "be171c49fd519560af283dc0d43fc4adc3cccb9a"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "5e95069b9c5b5a7d7010816413b3ce3b450ce2f752b4496ef699dd16b73c0d83"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-linux-musl.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "54151e0e4557f08b91343e8bd0780f72d1ccecb9"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "f97227fbde773a1fc23296f827e44a60f1eb67b90f9671051094bb2c3f169b7d"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.armv7l-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "4c36df5b23d99fcf8ac6c83619f3e36b758e8ebc"
os = "windows"

    [[armadillo.download]]
    sha256 = "31054de5bd89e9b768226c50af2aafec24bb96e17d8acad8c957dc7b41785222"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-w64-mingw32.tar.gz"
