[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "09e70826733b7207aea7b02e2d280707c9ffc42f"
os = "macos"

    [[armadillo.download]]
    sha256 = "7e27f4c23725023efdb9455b25615499b07112b3161f7cc7a4302af5542f22ef"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.aarch64-apple-darwin.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "e923dd74b9e8829bd538caf83e67e58f61ce546f"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "debc5b6d0c8d93514630cc3ea3b55036e4b2e04b9d26b15b5e97e4906d84c3dd"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.aarch64-linux-gnu.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "3e795f95a48e6eb069d170bddec1fcedcfb7f5b1"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "981d69652009f733fbaaf5fd9914d3c5a9c96690bcf4afce24af4518db00e5a7"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.aarch64-linux-musl.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "8ebb86280b5ec65534dc8f5103973da3d5fe882a"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "b3d6a67d7350159c14371e42c8289375e15fda7cfaab7aeed61023fb5e9eacc8"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.aarch64-unknown-freebsd.tar.gz"
[[armadillo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1d3bf987203817b495ded73dbd60c0ed89caf04b"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "203d3ba2ace122fb36039b36a99d69a7170b18ae9fb111e89cf32fff8df108fa"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.armv6l-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "60debb983f4bfbe8de008e56afe6ea2cfdf39cf3"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "24eb2e90dfc488ce81aa3ae882d4d4542e51d329eb9a5194efe686379301d17c"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.armv6l-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51c8ee57bfc7e4e1e00f5a701e357a60843ca6cc"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "887552d5d6f0844c578e3f939e926a82f93eccc3a7f59a7684ce884d98dd2446"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.armv7l-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce822451836d4e7d369d4a2c1fef2b2911eda2de"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "7765688b765fd3f2a56728b943faadabbc32c1682cfca335f652d259cb08e0fa"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.armv7l-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "1058a1fea96ec7751af08d4fe5b8faa93c686f3b"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "d47f5232eb2caf9bafe5bc97a0b4356e909ba92f101cad842273b052fe15b3ca"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.i686-linux-gnu.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "2ddcf814aeb813d7f30aef7277f202db07e455ab"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "6bed9e44b7061fddfd663bd68f1d3589ded2bb1a0ac99bdfa76646f6882e26b1"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.i686-linux-musl.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "ab6d1467b42f8cda681a06b86b795a22d9671b11"
os = "windows"

    [[armadillo.download]]
    sha256 = "212d83f11269b892ea621c55fb3dbcec80dfc9625e20e0b0d99dcc215d67df1f"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.i686-w64-mingw32.tar.gz"
[[armadillo]]
arch = "powerpc64le"
git-tree-sha1 = "f27c81aad04d640d352a8f1f677b933948064adf"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "7cc7d20a9d166863586bf0a9e2c0ea651e411e1da13f65e11a3dc6f41242db44"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.powerpc64le-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "9ad0f38ddaeba46ff72642977310dcdc5d2e8937"
os = "macos"

    [[armadillo.download]]
    sha256 = "71244df99e1b5c0e60156e0576eaa6781aa4abafeaeba30e51e3c0454b1b8501"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.x86_64-apple-darwin.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "7750c56d8ab6087fb5fbaa3324a21dc7d7f06447"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "9a0511c3e188f1bf4f60c22104569fc6800d049b95c31ec541f67700610f6b74"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.x86_64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "f0b2a917e5fd81c26db35db69696bdfb62ea66f8"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "365bbb341b466246ee3c2692be121e1d0fcae010a71c76ce4e5275c8eb16266a"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.x86_64-linux-musl.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "7c5a085b44fd78df523940ae42ce89a966f52ed5"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "e0de6b164a62e6ccb605a51c26cfd3db244264e5615836e94cc96f2e8edeaf94"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.x86_64-unknown-freebsd.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "1e4c3049181d2eef059e989dc2652a45ca1e0ce8"
os = "windows"

    [[armadillo.download]]
    sha256 = "809147fa8ce1d3ae18fbd1d844ec113104c1c95b1d95f0e3afa721ed7cc4aecc"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.2.1+0/armadillo.v14.2.1.x86_64-w64-mingw32.tar.gz"
