[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "5ffd1d1f49c0d0ebda4fb3c38f648aebb4ac9506"
os = "macos"

    [[armadillo.download]]
    sha256 = "e76abb29018531d87a06e3eef8ddd5597d71f6a165628d75247eedec3b921ba4"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.aarch64-apple-darwin.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "e00cfd671f92fbdc7885645cd6dc3f11f77eb0ea"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "2c2963fb967792f9f9932670dc1d5edeffcd0a793c1f02ec4b4ebc0a04670a17"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.aarch64-linux-gnu.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "d7d625ffd60e0a074eb41b45b85113d30c18ff34"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "df646b5c171e1fca1527f6a9e0ef9630235bfd67cc0ec48d41910024b43acb23"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.aarch64-linux-musl.tar.gz"
[[armadillo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6a9b29bb6aac1e03d163fb44f4687980275086f7"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "b6cb52a5e4908f680205f0f9019f8338fa9fd48c53940ad1cc83ad7475cda39b"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.armv6l-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f197f3f6b91294b58052628a27b9a15b25caea06"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "b8b55b952defef491e6eff63db310c519f49a5b8a79dda4fdaea333f380b8c1d"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.armv6l-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "68e45753767e426ff33e5bb85a9ed0c69ed081fd"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "2743c131a3685a49188ec5f949d36175fe56b3297d0a40fee961520b79129e3a"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.armv7l-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "83fd9d717fff94306efe71f7e131cdb0a159e251"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "b0dca2d2761903ec36ac15a22eecda2519103c5834f5c61475151cf15ab42dfe"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.armv7l-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "b967220fc560847051afe6f2c974f943ff0361ae"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "71c167193ce9052736ba5042b6c3a2fee784b84d0a13b429d51a7619709e5680"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.i686-linux-gnu.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "5e9d2f9cfeb01ea36add81e4aae4bf127f638766"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "f8fba591b15ff258ee7ce4513fac4a22ab156318a7fdf216a6823490fcb11b73"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.i686-linux-musl.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "b90d4c56405daf5d8c702697a576a9fe1da87ecf"
os = "windows"

    [[armadillo.download]]
    sha256 = "a617e2c987ba80bb6baf45b5fc48879e00b04a778cb71d6fad17f25986f0f96b"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.i686-w64-mingw32.tar.gz"
[[armadillo]]
arch = "powerpc64le"
git-tree-sha1 = "6c38d0668d0128e10b09f74d0d93d8413a07f26d"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "d07f4c661ef30dac0e7555bf6f96d8d58fa555d86ef553e8a82d9e73fed0fddf"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.powerpc64le-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "26a75983859bad53eed95537336255b2aac59ed5"
os = "macos"

    [[armadillo.download]]
    sha256 = "7384e9700534aa08a5c27a63f886fe022b4425066a45d4ed70599070376d75ef"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.x86_64-apple-darwin.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "624671f0ba3bc864d8ba7181f186b60a702180eb"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "fd1acd0934b1ed5b44d6bb46ec11c1ff02ce6541fe09c43ff1dc33784964c431"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.x86_64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "e47f74befaea8b42b3d7d6451aca1edbcce41395"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "3c82255acf4f6773a0fe5780d7a31ca6c06aa215588013148fa46d7b61fb09a7"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.x86_64-linux-musl.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "27b537f62a325ea380e17dea5759c59f2dc334c7"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "0109dcec7a7ef3dba627f3b11b00e530bf7b745b128b09f3dc58767ee3d2c2e6"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.x86_64-unknown-freebsd.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "45eecdef708911ceb90a13065fef7a0885cdf863"
os = "windows"

    [[armadillo.download]]
    sha256 = "8580a6c054fcb4092f9f03816b9985f06851837e48a983a4420744e02eb7482c"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v12.6.6+0/armadillo.v12.6.6.x86_64-w64-mingw32.tar.gz"
