[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "a940014a4f0fb1df1ed3d2ab6585eff7fcd560f3"
os = "macos"

    [[armadillo.download]]
    sha256 = "f3e18d773578cabe14eb808e55f59caa248ca3546ba3afadff6cc33fbeb3c15c"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.aarch64-apple-darwin.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "c798b1fe833187d7bb778fd4253d4df272b4dc7b"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "9fafa98d42fea3ff81130bb408f60bda0110770295bf04f76d279c23a585fee3"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.aarch64-linux-gnu.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "97713b317d74f98884d0126563e5ece4fb4b6c8a"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "256f862e42e23b031e77df70ffaf69fb8a53a15cdf75dbd571ed4a802c45f184"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.aarch64-linux-musl.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "9272bbd45428d8fe989522ef5d8835b23184ffd1"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "64c747e8596ad04e87692a83252ba969caf8fbc17852a85e613258ab5f5ce2fe"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.aarch64-unknown-freebsd.tar.gz"
[[armadillo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b389348cb2a939e54c7e0835bb6967fbef79c462"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "6a1af876efeeef5ecb2ded2dc32a7792373392ea846861782cb7ca4c1822f266"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.armv6l-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7fedea82c73a599fc2dddae01ddb7134eb3e204e"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "899c3134478fc4727aa1f7dfe11e6f8b584a6f8b8cffd0aaa142099cc561eeda"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.armv6l-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8d17895a479db8affff862de923aa4d5433ae55"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "242cef223e4bf82c9e1ee081c8dd09ae25dc0c45de9bafc567286674a58e7baf"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.armv7l-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df4398b1522c3e74df0b3849748e49880069ca18"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "399c76b7777dac921dc089a77c6c48b0d321477c0a43f5b7af7a58c22ad49d1a"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.armv7l-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "ecc94ae3fc590e92536735c58ce05098b09e401f"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "0f7cd35f0536e01ff67b18f9a8193ce990fa72837c38f5da7acff5db9c16647d"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.i686-linux-gnu.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "60f4c50fa10a71e0b10985b81b50ce71bc2b9f86"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "8d743499192e781188dc68b155466da640201abec1b53401951d2ea0e71b25e2"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.i686-linux-musl.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "fb06c6bc6343b9ae7d6898ed0b479c89132334af"
os = "windows"

    [[armadillo.download]]
    sha256 = "7aea8fca1b249b38723b8c03d3877cd7fe1f6ed6c29d6a3168ab15b7ce3f9c31"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.i686-w64-mingw32.tar.gz"
[[armadillo]]
arch = "powerpc64le"
git-tree-sha1 = "0a2f89e10bae35ee4e4987aeb4bb7843666c13bf"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "290b681f893c7904463cf02b785681dce8dda3b9628699e77158afb8c23d18b6"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.powerpc64le-linux-gnu.tar.gz"
[[armadillo]]
arch = "riscv64"
git-tree-sha1 = "be81381b973685dcc17146b73e786ee54bb2b13b"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "2efebb7e940786707271b5f9396e4a5194e9495b97ce6c0143cd96936223baca"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.riscv64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "d31063c009d28cac0a52542d55c805c8a5f673b7"
os = "macos"

    [[armadillo.download]]
    sha256 = "50600fcb6f01ae04d3b3e86b58ace60af0ec986a065452a6eadb86660842115d"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.x86_64-apple-darwin.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "3ae48b01638fbfa483778134de74f26dbc12d860"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "ed1e84bfbbc94be30ab5dc1cc4fd9d258f6662025d75ea419d4e6d2a37a29fed"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.x86_64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "e18141917a172579690ce559a0e83909578a846f"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "5ffbf5f990c674ed19c2f31b2f62890725e3a0c3e44ab8a6a8f2a60b4d0043a2"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.x86_64-linux-musl.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "87975702244de501b5432e84b7fb2150497529e9"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "f5452c7b0180b04c26ce76360f1f238329d67ba444eca1c157c59e299ab42932"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.x86_64-unknown-freebsd.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "dba285aa7aae870732d3c1f79acbb62015c56a1c"
os = "windows"

    [[armadillo.download]]
    sha256 = "333a1ddbc4b8ee57a5e664cdef7e99dd424be3a90b0361cdb247c131e6088c91"
    url = "https://github.com/JuliaBinaryWrappers/armadillo_jll.jl/releases/download/armadillo-v14.4.1+0/armadillo.v14.4.1.x86_64-w64-mingw32.tar.gz"
