# Autogenerated wrapper script for armadillo_jll for i686-w64-mingw32
export libarmadillo

using OpenBLAS_jll
JLLWrappers.@generate_wrapper_header("armadillo")
JLLWrappers.@declare_library_product(libarmadillo, "libarmadillo.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS_jll)
    JLLWrappers.@init_library_product(
        libarmadillo,
        "bin\\libarmadillo.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
